name: Deploy preprod pdesign on push feature

on:
  push:
    branches:
    - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 7.4 ]

    steps:
      - name: checkout preprod pdesign
        uses: actions/checkout@v3

      - name: Restore the Composer cache directory
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-'8.0'-composer-

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --prefer-dist --no-interaction

      - name: Zip artifact for deployment
        run: zip -r release.zip website/app/* website/vendor/* website/wordpress-core/* -x ".git/*" -x ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: create or replace backup release
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST_MINICOM }}
          username: ${{ secrets.DEPLOY_USER_MINICOM }}
          key: ${{ secrets.DEPLOY_KEY_MINICOM }}
          port: 22
#          script: "[ ! -d ~/preprod-pdesign/website ] || rm -rf ~/preprod-pdesign/old_website ~/preprod-pdesign/website/vendor ~/preprod-pdesign/website/wordpress-core && mv -fu ~/preprod/website ~/preprod/old_website"
          script: "[ ! -d ~/preprod-pdesign/website ] || rm -rf ~/preprod-pdesign/old_website ~/preprod-pdesign/website/vendor ~/preprod-pdesign/website/wordpress-core"

      - name: checkout preprod pdesign
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: unzip artifact for deployment
        run: |
         unzip -o release.zip

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./website
          remote_path: ~/preprod-pdesign
          remote_host: ${{ secrets.DEPLOY_HOST_MINICOM }}
          remote_user: ${{ secrets.DEPLOY_USER_MINICOM }}
          remote_key: ${{ secrets.DEPLOY_KEY_MINICOM }}

      - name: create new Symlink
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST_MINICOM }}
          username: ${{ secrets.DEPLOY_USER_MINICOM }}
          key: ${{ secrets.DEPLOY_KEY_MINICOM }}
          port: 22
          script: |
            ln -nsrf ~/preprod-pdesign/shared/.env ~/preprod-pdesign/website/.env
            ln -nsrf ~/preprod-pdesign/shared/uploads ~/preprod-pdesign/website/app/uploads
            ln -nsrf ~/preprod-pdesign/shared/cache ~/preprod-pdesign/website/app/cache
            ln -nsrf ~/preprod-pdesign/shared/w3tc-config ~/preprod-pdesign/website/app/w3tc-config
            rm ~/preprod-pdesign/website/.htaccess
            ln -nsrf ~/preprod-pdesign/shared/.htaccess ~/preprod-pdesign/website/.htaccess
            ln -nsrf ~/preprod-pdesign/shared/.htpasswd ~/preprod-pdesign/website/.htpasswd